### ISSUE TITLE
Navbar tasarım örneği

### ISSUE THREAD

**Issue by Thealoq** [serendiasquad/serendia-squad-frontend#2]
[![image](https://user-images.githubusercontent.com/79800238/192778418-73ad8a1f-fd36-4421-aa63-b2120fc3a413.png)]()
responsive tasarimda bu şekilde bence kötü gözüküyor şu şekilde gidilirse bence daha iyi olabilir 
![image](https://user-images.githubusercontent.com/79800238/192778555-a17665a0-4beb-42a8-ad4f-7561df822d62.png)
ss gözüktüğü gibi üstden gelirse daha iyi olurabilir

**Comment by aloshai** [comment]
Öneri için teşekkür ederim. 

Evet, mevcuttaki mobil için yapılmış Navbar'ın görüntüsü pek iç açıcı değil ancak henüz bitmemiş bir alan olduğu için net bir şey söyleyemeyeceğim. Paylaştığın tasarımdaki navbar'ı şu anki Navbar'ın çalışmaları bittikten sonra test amaçlı geliştireceğim. O zaman hangi tasarımın daha iyi olduğuna karar veririz. (benimde içime şu anki sinmiyor)

**Comment by aloshai** [comment]
Navbar tasarımını değiştirmeme kararı aldık belli başlı görünüş düzeltmeleri dışında bir değişiklik söz konusu olmayacak. Bu değişikliği sağlamamıza yardımcı olduğun için teşekkür ederiz.
